"""Relationship coverage model for the Parts Intelligence graph.

Every relationship the business model needs (the required list) plus every relationship found by inspecting the source data
(the additional list) is classified here. graph_build.py checks each row against the graph, writes
graph/audits/relationship_coverage_matrix.csv and fails the gate if anything is unaccounted for.
"""
from __future__ import annotations

IWD = "IMPLEMENTED_WITH_DATA"
IS_ = "IMPLEMENTED_SYNTHETIC"
SCH = "SCHEMA_ONLY_NO_DATA"
NA = "NOT_APPLICABLE"
BLK = "BLOCKED_BY_MISSING_DATA"


def K(t, f, to):
    return [(t, f, to)]


# (group, domain, source, relationship as the business model words it, target, status, graph keys, how it is implemented / why not, missing data)
CV = [
    # ---- required list
    ("REQUIRED", "Fitment", "Machine", "Machine -> Part (inverse traversal of FITS)", "Part", IWD, K("FITS", "Part", "Machine"), "Stored once as (Part)-[:FITS]->(Machine) and traversed in reverse. 216 confirmed, 3 conditional.", "KFT-120 has no parts in the catalogue"),
    ("REQUIRED", "Fitment", "Part", "FITS", "Machine", IWD, K("FITS", "Part", "Machine"), "Canonical fitment direction.", "KFT-120 has no parts in the catalogue"),
    ("REQUIRED", "Classification", "Part", "IN_CATEGORY", "Category", IWD, K("IN_CATEGORY", "Part", "Category"), "Source-stated category (level 1).", ""),
    ("REQUIRED", "Classification", "Part", "IN_SUBCATEGORY", "Category (sub-category)", IWD, K("IN_SUBCATEGORY", "Part", "Category"), "Rule-derived name head (level 2); awaits taxonomy approval.", ""),
    ("REQUIRED", "Specification", "Part", "HAS_SPECIFICATION", "PartSpecification", IWD, K("HAS_SPECIFICATION", "Part", "PartSpecification"), "Verbatim spec note plus parsed values.", ""),
    ("REQUIRED", "Legacy", "Part", "HAS_LEGACY_REFERENCE", "LegacyReference", IWD, K("HAS_LEGACY_REFERENCE", "Part", "LegacyReference"), "One legacy record per part.", "5 records are unresolved free text (no legacy number)"),
    ("REQUIRED", "Assembly", "Part", "PART_OF", "Assembly", IS_, K("PART_OF", "Part", "Assembly"), "Synthetic demo BOM.", "Only 43 of 100 parts are in an assembly"),
    ("REQUIRED", "Assembly", "Assembly", "Assembly -> Part (inverse of PART_OF; IDENTIFIED_BY_PART gives the assembly's own part number)", "Part", IS_, K("PART_OF", "Part", "Assembly") + K("IDENTIFIED_BY_PART", "Assembly", "Part"), "Contents are the inverse traversal of PART_OF; no second relationship is stored.", "Only 43 of 100 parts are in an assembly"),
    ("REQUIRED", "Sourcing", "Part", "SUPPLIED_BY", "Supplier", IS_, K("SUPPLIED_BY", "Part", "Supplier"), "Synthetic supplier links with cost, lead time, MOQ and primary flag.", ""),
    ("REQUIRED", "Sourcing", "Supplier", "Supplier -> Part (inverse of SUPPLIED_BY)", "Part", IS_, K("SUPPLIED_BY", "Part", "Supplier"), "Inverse traversal; no second relationship stored.", ""),
    ("REQUIRED", "Sourcing", "Part", "STOCKED_BY", "Dealer", IS_, K("STOCKED_BY", "Part", "Dealer"), "Synthetic dealer stocking list with quantities.", "1 of 100 parts has no dealer listing; 26 dealer zero-rows excluded as UNKNOWN"),
    ("REQUIRED", "Sourcing", "Dealer", "Dealer -> Part (inverse of STOCKED_BY)", "Part", IS_, K("STOCKED_BY", "Part", "Dealer"), "Inverse traversal.", ""),
    ("REQUIRED", "Inventory", "Part", "AVAILABLE_AT", "Warehouse", IS_, K("AVAILABLE_AT", "Part", "Warehouse"), "Synthetic warehouse stock (on_hand, reserved, available).", ""),
    ("REQUIRED", "Inventory", "Warehouse", "Warehouse -> Part (inverse of AVAILABLE_AT)", "Part", IS_, K("AVAILABLE_AT", "Part", "Warehouse"), "Inverse traversal.", ""),
    ("REQUIRED", "Manufacturing", "Plant", "Plant -> Machine (inverse of MANUFACTURED_AT)", "Machine", IWD, K("MANUFACTURED_AT", "Machine", "Plant"), "Inverse traversal; no second relationship stored.", ""),
    ("REQUIRED", "Manufacturing", "Machine", "MANUFACTURED_AT", "Plant", IWD, K("MANUFACTURED_AT", "Machine", "Plant"), "Catalogue Plant column.", ""),
    ("REQUIRED", "Location", "Dealer", "LOCATED_AT_ADDRESS (the dealer's place)", "Address", IS_, K("LOCATED_AT_ADDRESS", "Dealer", "Address"), "Catalogue Location nodes cover plants and countries only; dealers sit at synthetic placeholder addresses (city, region, postal code, country).", ""),
    ("REQUIRED", "Location", "Supplier", "LOCATED_AT_ADDRESS (the supplier's place)", "Address", IS_, K("LOCATED_AT_ADDRESS", "Supplier", "Address"), "Synthetic placeholder addresses.", ""),
    ("REQUIRED", "Location", "Warehouse", "LOCATED_AT_ADDRESS (the warehouse's place)", "Address", IS_, K("LOCATED_AT_ADDRESS", "Warehouse", "Address"), "Synthetic placeholder addresses.", ""),
    ("REQUIRED", "Part relationships", "Part", "SAME_NAME_GROUP_AS", "Part", IWD, K("SAME_NAME_GROUP_AS", "Part", "Part"), "Rule-derived naming group. Not an alternative; interchangeability UNKNOWN.", ""),
    ("REQUIRED", "Part relationships", "Part", "RELATED_COMPONENT", "Part", IWD, K("RELATED_COMPONENT", "Part", "Part"), "Catalogue mentions a related component. Not an alternative; interchangeability UNKNOWN.", ""),
    ("REQUIRED", "Part relationships", "Part", "CO_ORDERED_WITH", "Part", IS_, K("CO_ORDERED_WITH", "Part", "Part"), "Synthetic co-purchase signal, stored once per pair.", ""),
    ("REQUIRED", "Inventory", "Part", "Part -> Inventory (stock quantities live on AVAILABLE_AT and STOCKED_BY; no separate Inventory node)", "Inventory", IS_, K("AVAILABLE_AT", "Part", "Warehouse") + K("STOCKED_BY", "Part", "Dealer"), "Inventory is a property of the stock relationship, so a stock record cannot float free of its part and place.", "26 dealer zero-rows excluded as UNKNOWN"),
    ("REQUIRED", "Pricing", "Part", "Part -> Price (inverse of PRICES_PART)", "Price", IS_, K("PRICES_PART", "Price", "Part"), "Synthetic demo list price.", ""),
    ("REQUIRED", "Orders", "Customer", "Customer -> Order (inverse of ORDERED_BY)", "Order", IS_, K("ORDERED_BY", "Order", "Customer"), "Inverse traversal.", ""),
    ("REQUIRED", "Orders", "Order", "ORDERED_BY", "Customer", IS_, K("ORDERED_BY", "Order", "Customer"), "Synthetic orders.", ""),
    ("REQUIRED", "Orders", "Order", "CONTAINS_LINE", "OrderLine", IS_, K("CONTAINS_LINE", "Order", "OrderLine"), "Synthetic order lines.", ""),
    ("REQUIRED", "Orders", "OrderLine", "REFERENCES_PART", "Part", IS_, K("REFERENCES_PART", "OrderLine", "Part"), "Each order line names one part.", ""),
    ("REQUIRED", "Allocation", "Order", "Order -> Allocation", "Allocation", SCH, [], "No Allocation entity exists. Allocation status lives on the order line (allocation_status) and on ALLOCATED_FROM; nothing is invented to fill the gap.", "Allocation records (quantity per warehouse, timestamps)"),
    ("REQUIRED", "Allocation", "Allocation", "Allocation -> Warehouse (line-level ALLOCATED_FROM)", "Warehouse", IS_, K("ALLOCATED_FROM", "OrderLine", "Warehouse"), "Implemented on the order line, not on an Allocation node. Only RESERVED or SHIPPED lines; not-yet-allocated lines use PLANNED_FULFILMENT_FROM.", "No separate Allocation entity"),
    ("REQUIRED", "Fulfilment", "Order", "Order -> Fulfilment", "Fulfilment", SCH, [], "No Fulfilment entity exists in the data. The planned source (PLANNED_FULFILMENT_FROM) and the dispatch warehouse (DISPATCHED_FROM) are the only fulfilment facts.", "Fulfilment records"),
    ("REQUIRED", "Fulfilment", "Fulfilment", "Fulfilment -> Warehouse (line-level PLANNED_FULFILMENT_FROM)", "Warehouse", IS_, K("PLANNED_FULFILMENT_FROM", "OrderLine", "Warehouse"), "Planned source of lines that are not yet allocated.", "No separate Fulfilment entity"),
    ("REQUIRED", "Shipping", "Order", "HAS_SHIPMENT", "Shipment", IS_, K("HAS_SHIPMENT", "Order", "Shipment"), "Synthetic; only 4 of 8 orders have shipments (not filled).", "Shipments for 4 of 8 orders"),
    ("REQUIRED", "Shipping", "Shipment", "CARRIED_BY", "Carrier", IS_, K("CARRIED_BY", "Shipment", "Carrier"), "One fictional carrier; its key is derived from its name because the workbook has no carrier id. Real carriers do not exist in the data.", "Real carriers"),
    ("REQUIRED", "Shipping", "Shipment", "HAS_TRACKING_EVENT", "TrackingEvent", IS_, K("HAS_TRACKING_EVENT", "Shipment", "TrackingEvent"), "Synthetic tracking events.", ""),
    ("REQUIRED", "Service", "ServicePlan", "FOR_MACHINE", "Machine", IS_, K("FOR_MACHINE", "ServicePlan", "Machine"), "Synthetic service plans (interval templates), not jobs.", ""),
    ("REQUIRED", "Service", "ServicePlan", "REQUIRES_PART", "Part", IS_, K("REQUIRES_PART", "ServicePlan", "Part"), "Synthetic; covers 33 of 100 parts.", "Service plans for 67 of 100 parts"),
    ("REQUIRED", "Service", "ServiceJob", "FOR_MACHINE", "Machine", SCH, [], "No service jobs exist; service plans are not relabelled as jobs.", "ServiceJob records"),
    ("REQUIRED", "Service", "ServiceJob", "REQUIRES_PART", "Part", SCH, [], "No service jobs exist.", "ServiceJob records"),
    ("REQUIRED", "Service", "ServiceJob", "PERFORMED_BY", "Dealer", SCH, [], "No service jobs exist, and dealers are not linked to service work in the data (dealers serve machine families only).", "ServiceJob records and dealer service assignments"),
    ("REQUIRED", "Compliance", "Part", "HAS_COMPLIANCE", "ComplianceRequirement", IS_, K("HAS_COMPLIANCE", "Part", "ComplianceRequirement"), "Synthetic compliance records.", ""),
    ("REQUIRED", "Risk", "Part", "HAS_RISK", "SourceRisk", SCH, [], "No risk data exists.", "Risk records"),
    ("REQUIRED", "Part relationships", "Part", "ALTERNATIVE_TO", "Part", SCH, [], "No authoritative alternative data. Never inferred from names, categories or shared fitment.", "Authoritative alternative / interchangeability evidence"),
    ("REQUIRED", "Part relationships", "Part", "SUPERSEDES / SUPERSEDED_BY", "Part", SCH, [], "No supersession data. Legacy references are previous numbers of the SAME part, not a successor part.", "Supersession records"),
    ("REQUIRED", "Machine hierarchy", "Machine", "Machine -> Configuration", "Configuration", SCH, [], "No configuration level exists in any source.", "Configuration records"),
    ("REQUIRED", "Machine hierarchy", "Machine", "Machine -> Serial Range (inverse of VARIANT_OF)", "MachineVariant", IS_, K("VARIANT_OF", "MachineVariant", "Machine"), "30 synthetic variants with serial_from / serial_to. Individual serial-numbered machines do not exist.", "Serial-numbered machine units"),
    ("REQUIRED", "Requests", "Customer", "Customer -> Request", "Request", SCH, [], "No requests exist. Carts are not requests.", "Request records"),
    ("REQUIRED", "Requests", "Request", "Request -> Part", "Part", SCH, [], "No requests exist.", "Request lines"),
    ("REQUIRED", "Installation", "Installation", "Installation -> Machine", "Machine", SCH, [], "No installations exist.", "Installation records"),
    ("REQUIRED", "Installation", "Installation", "Installation -> Part", "Part", SCH, [], "No installations exist.", "Installation records"),
    # ---- found by inspecting the source data (not on the required list)
    ("ADDITIONAL", "Catalogue structure", "Machine", "OF_TYPE", "MachineType", IWD, K("OF_TYPE", "Machine", "MachineType"), "Catalogue Machine Type column.", ""),
    ("ADDITIONAL", "Catalogue structure", "Machine", "MEMBER_OF_FAMILY", "MachineFamily", IWD, K("MEMBER_OF_FAMILY", "Machine", "MachineFamily"), "Derived from the model-code prefix (provenance DERIVED).", ""),
    ("ADDITIONAL", "Catalogue structure", "Machine", "BRANDED_AS", "BusinessUnit", IWD, K("BRANDED_AS", "Machine", "BusinessUnit"), "Catalogue Brand / Origin column.", ""),
    ("ADDITIONAL", "Catalogue structure", "MachineFamily", "PRODUCT_FAMILY_OF", "BusinessUnit", IWD, K("PRODUCT_FAMILY_OF", "MachineFamily", "BusinessUnit"), "Derived.", ""),
    ("ADDITIONAL", "Catalogue structure", "Plant", "OWNED_BY", "BusinessUnit", IWD, K("OWNED_BY", "Plant", "BusinessUnit"), "Project brief (USER_PROVIDED).", ""),
    ("ADDITIONAL", "Catalogue structure", "BusinessUnit", "HOME_PLANT", "Plant", IWD, K("HOME_PLANT", "BusinessUnit", "Plant"), "ADDED by this audit: business_units.home_plant_id was only a column.", ""),
    ("ADDITIONAL", "Catalogue structure", "Plant", "LOCATED_IN", "Location", IWD, K("LOCATED_IN", "Plant", "Location"), "Catalogue city location.", ""),
    ("ADDITIONAL", "Catalogue structure", "Location", "IN_COUNTRY", "Location", IWD, K("IN_COUNTRY", "Location", "Location"), "City in country.", ""),
    ("ADDITIONAL", "Catalogue structure", "Category", "SUBCATEGORY_OF", "Category", IWD, K("SUBCATEGORY_OF", "Category", "Category"), "Derived sub-categories under source categories.", ""),
    ("ADDITIONAL", "Catalogue structure", "Part", "ORIGINATES_AT", "Plant", IWD, K("ORIGINATES_AT", "Part", "Plant"), "Catalogue Plant of Origin.", ""),
    ("ADDITIONAL", "Legacy", "LegacyReference", "ISSUED_BY_BUSINESS_UNIT", "BusinessUnit", IWD, K("ISSUED_BY_BUSINESS_UNIT", "LegacyReference", "BusinessUnit"), "Mostly rule-derived from prefix and plant (provenance DERIVED).", ""),
    ("ADDITIONAL", "Location", "Warehouse", "LOCATED_AT_PLANT", "Plant", IS_, K("LOCATED_AT_PLANT", "Warehouse", "Plant"), "Synthetic; 3 of 4 warehouses.", ""),
    ("ADDITIONAL", "Location", "Warehouse (WH-004)", "LOCATED_AT_PLANT", "Plant", BLK, [], "The source states no plant for the Zwolle warehouse; none is guessed.", "plant_id for WH-004"),
    ("ADDITIONAL", "Location", "Plant", "LOCATED_AT_ADDRESS", "Address", IS_, K("LOCATED_AT_ADDRESS", "Plant", "Address"), "Synthetic placeholder addresses for the fictional plants.", ""),
    ("ADDITIONAL", "Location", "Customer", "LOCATED_AT_ADDRESS", "Address", IS_, K("LOCATED_AT_ADDRESS", "Customer", "Address"), "Synthetic.", ""),
    ("ADDITIONAL", "Location", "Address", "IN_REGION", "Region", IS_, K("IN_REGION", "Address", "Region"), "Synthetic region (VAT reference).", ""),
    ("ADDITIONAL", "Location", "Warehouse", "SHIPS_TO_COUNTRY", "Location (NL, DE)", IS_, K("SHIPS_TO_COUNTRY", "Warehouse", "Location"), "ADDED by this audit: warehouses.ships_to was only text.", ""),
    ("ADDITIONAL", "Location", "Warehouse", "SHIPS_TO_COUNTRY (Belgium)", "Location (BE)", BLK, [], "The workbook says every warehouse ships to BE, but the catalogue has no Belgium location node; none is invented.", "A Belgium country Location"),
    ("ADDITIONAL", "Sourcing", "Supplier", "SUPPLIES_CATEGORY", "Category", IS_, K("SUPPLIES_CATEGORY", "Supplier", "Category"), "ADDED by this audit: declared category scope (SYN_suppliers.categories_supplied). Does NOT imply SUPPLIED_BY for any part.", ""),
    ("ADDITIONAL", "Sourcing", "SupplierBackorder", "PLACED_WITH", "Supplier", IS_, K("PLACED_WITH", "SupplierBackorder", "Supplier"), "Synthetic backorders.", ""),
    ("ADDITIONAL", "Sourcing", "SupplierBackorder", "FOR_PART", "Part", IS_, K("FOR_PART", "SupplierBackorder", "Part"), "Synthetic backorders.", ""),
    ("ADDITIONAL", "Sourcing", "Dealer", "SERVES_FAMILY", "MachineFamily", IS_, K("SERVES_FAMILY", "Dealer", "MachineFamily"), "Family level only. Never read as dealer-supports-model or dealer-stocks-part.", "Dealer-to-model support is not in the data"),
    ("ADDITIONAL", "Compliance", "ComplianceRequirement", "COVERS_CATEGORY", "Category", IS_, K("COVERS_CATEGORY", "ComplianceRequirement", "Category"), "ADDED by this audit: declared category scope (SYN_compliance.categories_covered).", ""),
    ("ADDITIONAL", "Part profile", "PartCatalogProfile", "PROFILES_PART", "Part", IS_, K("PROFILES_PART", "PartCatalogProfile", "Part"), "Synthetic store profile kept apart from the catalogue Part.", ""),
    ("ADDITIONAL", "Pricing", "Price", "PRICES_PART", "Part", IS_, K("PRICES_PART", "Price", "Part"), "Synthetic.", ""),
    ("ADDITIONAL", "Machine detail", "Machine", "HAS_MACHINE_SPECIFICATION", "MachineSpecification", IS_, K("HAS_MACHINE_SPECIFICATION", "Machine", "MachineSpecification"), "Synthetic machine specs (not engineering data).", ""),
    ("ADDITIONAL", "Machine detail", "MachineVariant", "VARIANT_OF", "Machine", IS_, K("VARIANT_OF", "MachineVariant", "Machine"), "Synthetic.", ""),
    ("ADDITIONAL", "Identification", "IdentificationRequirement", "FOR_PART", "Part", IS_, K("FOR_PART", "IdentificationRequirement", "Part"), "Synthetic.", ""),
    ("ADDITIONAL", "Identification", "IdentificationRequirement", "FOR_MACHINE", "Machine", IS_, K("FOR_MACHINE", "IdentificationRequirement", "Machine"), "Synthetic.", ""),
    ("ADDITIONAL", "Identification", "IdentificationRequirement", "ADMITS_VARIANT", "MachineVariant", IS_, K("ADMITS_VARIANT", "IdentificationRequirement", "MachineVariant"), "Synthetic; does not add catalogue fitment.", ""),
    ("ADDITIONAL", "Orders", "Order", "DELIVERS_TO_ADDRESS", "Address", IS_, K("DELIVERS_TO_ADDRESS", "Order", "Address"), "Synthetic.", ""),
    ("ADDITIONAL", "Orders", "Order", "HAS_STATUS_EVENT", "OrderStatusEvent", IS_, K("HAS_STATUS_EVENT", "Order", "OrderStatusEvent"), "Synthetic status history.", ""),
    ("ADDITIONAL", "Orders", "OrderStatusEvent", "RECORDS_STATUS", "OrderStatus", IS_, K("RECORDS_STATUS", "OrderStatusEvent", "OrderStatus"), "Status vocabulary from the brief.", ""),
    ("ADDITIONAL", "Orders", "OrderLine", "PLANNED_FULFILMENT_FROM", "Warehouse", IS_, K("PLANNED_FULFILMENT_FROM", "OrderLine", "Warehouse"), "Synthetic; lines not yet allocated.", ""),
    ("ADDITIONAL", "Shipping", "Shipment", "SHIPS_LINE", "OrderLine", IS_, K("SHIPS_LINE", "Shipment", "OrderLine"), "Synthetic; 9 of 14 order lines.", "5 order lines have no shipment"),
    ("ADDITIONAL", "Shipping", "Shipment", "DISPATCHED_FROM", "Warehouse", IS_, K("DISPATCHED_FROM", "Shipment", "Warehouse"), "Synthetic.", ""),
    ("ADDITIONAL", "Shipping", "Shipment", "DELIVERS_TO_CUSTOMER", "Customer", IS_, K("DELIVERS_TO_CUSTOMER", "Shipment", "Customer"), "Synthetic.", ""),
    ("ADDITIONAL", "Fulfilment", "DeliveryEstimate", "FROM_WAREHOUSE", "Warehouse", IS_, K("FROM_WAREHOUSE", "DeliveryEstimate", "Warehouse"), "Synthetic delivery estimates.", ""),
    ("ADDITIONAL", "Fulfilment", "DeliveryEstimate", "TO_CUSTOMER", "Customer", IS_, K("TO_CUSTOMER", "DeliveryEstimate", "Customer"), "Synthetic.", ""),
    ("ADDITIONAL", "Fulfilment", "DeliveryEstimate", "TO_DEALER", "Dealer", IS_, K("TO_DEALER", "DeliveryEstimate", "Dealer"), "Synthetic.", ""),
    ("ADDITIONAL", "Ordering", "Cart", "OPENED_BY", "Customer", IS_, K("OPENED_BY", "Cart", "Customer"), "Synthetic carts.", ""),
    ("ADDITIONAL", "Ordering", "Cart", "CONTAINS_LINE", "CartLine", IS_, K("CONTAINS_LINE", "Cart", "CartLine"), "Synthetic carts.", ""),
    ("ADDITIONAL", "Ordering", "CartLine", "REFERENCES_PART", "Part", IS_, K("REFERENCES_PART", "CartLine", "Part"), "Synthetic carts.", ""),
    ("ADDITIONAL", "Search", "Part", "HAS_ALIAS", "SearchAlias", IS_, K("HAS_ALIAS", "Part", "SearchAlias"), "Synthetic aliases.", ""),
    ("ADDITIONAL", "Search", "Machine", "HAS_ALIAS", "SearchAlias", IS_, K("HAS_ALIAS", "Machine", "SearchAlias"), "Synthetic aliases.", ""),
    # ---- deliberately not relationships
    ("ADDITIONAL", "Fulfilment", "DeliveryEstimate", "DeliveryEstimate -> ShippingRate", "ShippingRate", NA, [], "The workbook states no link; the rate is only derivable from the distance band. A derivable link is not a stated one, so it is not created.", ""),
    ("ADDITIONAL", "Access control", "User / Role", "User -> Customer, User -> Role", "Customer / Role", NA, [], "SYN_users / SYN_roles are access-control demo data, not part of Parts Intelligence for this phase.", ""),
    ("ADDITIONAL", "Geography", "Any place", "DISTANCE_TO (SYN_distances, 946 pairs)", "Any place", NA, [], "Proximity must never create a business relationship; distances are not imported.", ""),
    ("ADDITIONAL", "Inference guard", "Supplier / Dealer", "Supplier or Dealer -> Plant / Machine / Customer by proximity or country", "Plant / Machine / Customer", NA, [], "Forbidden inference: no supplier, dealer or customer relationship is derived from location.", ""),
    ("ADDITIONAL", "Inference guard", "Part", "Part -> Part by shared machines or similar names", "Part", NA, [], "Forbidden inference: shared fitment or naming never creates an alternative or interchangeable relationship.", ""),
]

# Every foreign-key-like column of the workbook and what happens to it. A column that is neither mapped nor explained fails the gate.
FK_ACCOUNT = {
    ("business_units", "home_plant_id"): "HOME_PLANT", ("plants", "business_unit_id"): "OWNED_BY", ("plants", "location_id"): "LOCATED_IN", ("locations", "parent_location_id"): "IN_COUNTRY",
    ("machine_families", "business_unit_id"): "PRODUCT_FAMILY_OF", ("machines", "family_id"): "MEMBER_OF_FAMILY", ("machines", "machine_type_id"): "OF_TYPE", ("machines", "business_unit_id"): "BRANDED_AS", ("machines", "plant_id"): "MANUFACTURED_AT",
    ("categories", "parent_category_id"): "SUBCATEGORY_OF", ("parts", "category_id"): "IN_CATEGORY", ("parts", "subcategory_id"): "IN_SUBCATEGORY", ("parts", "plant_id"): "ORIGINATES_AT",
    ("machine_part_fitment", "machine_id"): "FITS", ("machine_part_fitment", "part_id"): "FITS", ("part_specifications", "part_id"): "HAS_SPECIFICATION",
    ("legacy_part_mapping", "current_part_id"): "HAS_LEGACY_REFERENCE", ("legacy_part_mapping", "legacy_business_unit_id"): "ISSUED_BY_BUSINESS_UNIT",
    ("part_relationships", "from_part_id"): "SAME_NAME_GROUP_AS / RELATED_COMPONENT", ("part_relationships", "to_part_id"): "SAME_NAME_GROUP_AS / RELATED_COMPONENT",
    ("search_index", "entity_id"): "EXCLUDED: derived search text, not imported", ("relationships_all", "from_id"): "EXCLUDED: the workbook's own edge list, reconciled not imported", ("relationships_all", "to_id"): "EXCLUDED: the workbook's own edge list, reconciled not imported",
    ("SYN_warehouses", "plant_id"): "LOCATED_AT_PLANT", ("SYN_warehouses", "ships_to"): "SHIPS_TO_COUNTRY", ("SYN_warehouses", "address_id"): "LOCATED_AT_ADDRESS",
    ("SYN_suppliers", "categories_supplied"): "SUPPLIES_CATEGORY", ("SYN_suppliers", "address_id"): "LOCATED_AT_ADDRESS",
    ("SYN_part_supplier", "part_id"): "SUPPLIED_BY", ("SYN_part_supplier", "supplier_id"): "SUPPLIED_BY", ("SYN_pricing", "part_id"): "PRICES_PART",
    ("SYN_dealers", "families_served"): "SERVES_FAMILY", ("SYN_dealers", "address_id"): "LOCATED_AT_ADDRESS", ("SYN_customers", "address_id"): "LOCATED_AT_ADDRESS",
    ("SYN_addresses", "owner_type"): "LOCATED_AT_ADDRESS (plants here; other owners through their own address_id)", ("SYN_addresses", "owner_id"): "LOCATED_AT_ADDRESS (plants here; other owners through their own address_id)", ("SYN_addresses", "owner_name"): "EXCLUDED: a label, not an identifier",
    ("SYN_orders", "customer_id"): "ORDERED_BY", ("SYN_orders", "delivery_address_id"): "DELIVERS_TO_ADDRESS",
    ("SYN_order_items", "order_id"): "CONTAINS_LINE", ("SYN_order_items", "part_id"): "REFERENCES_PART", ("SYN_order_items", "fulfilment_location_id"): "ALLOCATED_FROM / PLANNED_FULFILMENT_FROM",
    ("SYN_order_status_history", "order_id"): "HAS_STATUS_EVENT", ("SYN_shipments", "order_id"): "HAS_SHIPMENT", ("SYN_shipments", "order_item_id"): "SHIPS_LINE", ("SYN_shipments", "from_location_id"): "DISPATCHED_FROM", ("SYN_shipments", "to_customer_id"): "DELIVERS_TO_CUSTOMER",
    ("SYN_carts", "customer_id"): "OPENED_BY", ("SYN_cart_items", "cart_id"): "CONTAINS_LINE", ("SYN_cart_items", "part_id"): "REFERENCES_PART",
    ("SYN_inventory", "location_id"): "AVAILABLE_AT / STOCKED_BY (quantities)", ("SYN_inventory", "part_id"): "AVAILABLE_AT / STOCKED_BY (quantities)",
    ("SYN_part_dealer", "dealer_id"): "STOCKED_BY", ("SYN_part_dealer", "part_id"): "STOCKED_BY",
    ("SYN_distances", "from_node_id"): "EXCLUDED: proximity never creates a relationship", ("SYN_distances", "to_node_id"): "EXCLUDED: proximity never creates a relationship",
    ("SYN_machine_specifications", "machine_id"): "HAS_MACHINE_SPECIFICATION", ("SYN_assembly_master", "assembly_part_id"): "IDENTIFIED_BY_PART",
    ("SYN_assembly_components", "assembly_id"): "PART_OF", ("SYN_assembly_components", "component_part_id"): "PART_OF",
    ("SYN_services", "machine_id"): "FOR_MACHINE", ("SYN_service_parts", "service_id"): "REQUIRES_PART", ("SYN_service_parts", "part_id"): "REQUIRES_PART",
    ("SYN_part_relationships", "from_part_id"): "CO_ORDERED_WITH", ("SYN_part_relationships", "to_part_id"): "CO_ORDERED_WITH",
    ("SYN_part_catalog", "primary_supplier_id"): "SUPPLIED_BY.is_primary (checked identical for all 100 parts; not stored twice)",
    ("SYN_supplier_backorders", "part_id"): "FOR_PART", ("SYN_supplier_backorders", "supplier_id"): "PLACED_WITH",
    ("SYN_machine_variants", "machine_id"): "VARIANT_OF", ("SYN_identification_requirements", "part_id"): "FOR_PART", ("SYN_identification_requirements", "machine_id"): "FOR_MACHINE", ("SYN_identification_requirements", "fits_variant_ids"): "ADMITS_VARIANT",
    ("SYN_compliance", "categories_covered"): "COVERS_CATEGORY", ("SYN_part_compliance", "part_id"): "HAS_COMPLIANCE", ("SYN_part_compliance", "compliance_id"): "HAS_COMPLIANCE",
    ("SYN_users", "role_id"): "EXCLUDED: access control, not required for this phase", ("SYN_users", "customer_id"): "EXCLUDED: access control, not required for this phase",
    ("SYN_delivery_options", "from_warehouse_id"): "FROM_WAREHOUSE", ("SYN_delivery_options", "to_id"): "TO_CUSTOMER / TO_DEALER", ("SYN_shipment_events", "shipment_id"): "HAS_TRACKING_EVENT", ("SYN_search_aliases", "entity_id"): "HAS_ALIAS",
}
