"""Generates src/data/catalog.generated.ts from the supplied Noordveld catalog workbook.

Run: npm run data   (requires: pip install openpyxl)
Only the workbook is read; nothing is invented or renamed.
"""
import json
from pathlib import Path
import openpyxl

root = Path(__file__).resolve().parent.parent
# Temporary: the frontend still presents catalogue data generated from the backend master file. The backend API replaces this later.
backend_data = root.parent / "backend" / "data"
wb = openpyxl.load_workbook(backend_data / "catalogue" / "noordveld-parts-catalog.xlsx", data_only=True)


def rows(sheet):
    data = list(wb[sheet].iter_rows(values_only=True))
    head = [str(h).strip() for h in data[0]]
    return [dict(zip(head, r)) for r in data[1:] if any(c is not None for c in r)]


machines = [
    {
        "model": r["Model"].strip(),
        "machineType": r["Machine Type"].strip(),
        "plant": r["Plant"].strip(),
        "brandOrigin": r["Brand / Origin"].strip(),
    }
    for r in rows("Machine Types")
]
parts = [
    {
        "partNo": r["Unified Part No."].strip(),
        "name": r["Part Name"].strip(),
        "category": r["Category"].strip(),
        "plantOfOrigin": r["Plant of Origin"].strip(),
        "compatibleModels": [m.strip() for m in str(r["Compatible Machine Types"]).split(",") if m.strip()],
        "specNote": (r["Spec Note"] or "").strip(),
    }
    for r in rows("Parts Catalog")
]

out = "// GENERATED by scripts/build-data.py from backend/data/catalogue/noordveld-parts-catalog.xlsx. Do not edit by hand.\n\n"
out += "export const catalogMachines = " + json.dumps(machines, indent=2, ensure_ascii=False) + " as const\n\n"
out += "export const catalogParts = " + json.dumps(parts, indent=2, ensure_ascii=False) + " as const\n"
(root / "src" / "data" / "catalog.generated.ts").write_text(out, encoding="utf-8")
print(f"{len(machines)} machines, {len(parts)} parts")
