// GENERATED by scripts/build-film-data.py from backend/data/processed/noordveld-complete-dataset-synthetic-demo.xlsx. Do not edit by hand.
// Every value is a row of the workbook. Supply-side records (suppliers, dealers, stock, prices, delivery) are synthetic demo data.

export const filmData = {
  "counts": {
    "machines": 15,
    "parts": 100,
    "fitments": 219,
    "specifications": 279
  },
  "machine": {
    "model": "NV-4500",
    "name": "NV-4500 Wheel Loader",
    "type": "Wheel Loader",
    "plant": "Assen (NL)",
    "country": "Netherlands",
    "partsFitted": 52,
    "inStock": 48,
    "legacyMapped": 52,
    "slug": "nv-4500",
    "services": [
      "Basic service",
      "Intermediate service",
      "Major service",
      "Overhaul"
    ],
    "serviceInterval": [
      250,
      500,
      1000,
      2000
    ]
  },
  "part": {
    "id": "PRT-002",
    "no": "NVM-1010-HY",
    "name": "Hydraulic hose, high-pressure 19mm",
    "category": "Hydraulics",
    "subcategory": "Hydraulic hose",
    "legacyNo": "AS-771",
    "legacyBusiness": "Noordveld",
    "plant": "Assen (NL)",
    "fits": [
      "NV-3200",
      "NV-4500"
    ],
    "specNote": "3/4 in, 2-wire braid, 900mm",
    "priceExVat": 742.28,
    "weightKg": 11.3,
    "status": "VERIFIED",
    "availability": "IN_STOCK",
    "usedInService": false
  },
  "siblings": [
    {
      "no": "NVM-1010-HY",
      "name": "Hydraulic hose, high-pressure 19mm"
    },
    {
      "no": "NVM-1030-HY",
      "name": "Main lift cylinder, double-acting"
    },
    {
      "no": "NVM-1040-HY",
      "name": "Tilt cylinder, double-acting"
    },
    {
      "no": "NVM-1070-HY",
      "name": "Directional control valve, 4-spool"
    },
    {
      "no": "NVM-1080-HY",
      "name": "Relief valve, 210 bar"
    },
    {
      "no": "NVM-1120-HY",
      "name": "Tilt cylinder seal kit"
    }
  ],
  "supplier": {
    "id": "SUP-001",
    "name": "Veldstra Hydraulics",
    "city": "Groningen",
    "lat": 53.2194,
    "lon": 6.5665,
    "leadDays": 28,
    "partNo": "001-1010-HY"
  },
  "stock": [
    {
      "id": "DLR-002",
      "kind": "dealer",
      "name": "IJsselvallei Equipment",
      "city": "Zwolle",
      "lat": 52.5168,
      "lon": 6.083,
      "available": 7,
      "pickup": true
    },
    {
      "id": "DLR-004",
      "kind": "dealer",
      "name": "Brabant Heavy Parts",
      "city": "Eindhoven",
      "lat": 51.4416,
      "lon": 5.4697,
      "available": 8,
      "pickup": true
    },
    {
      "id": "DLR-007",
      "kind": "dealer",
      "name": "Drenthe Techniek",
      "city": "Emmen",
      "lat": 52.7792,
      "lon": 6.9069,
      "available": 5,
      "pickup": true
    },
    {
      "id": "WH-001",
      "kind": "warehouse",
      "name": "Noordveld Central Warehouse Assen",
      "city": "Assen",
      "lat": 52.9925,
      "lon": 6.5642,
      "available": 56,
      "pickup": false
    },
    {
      "id": "WH-002",
      "kind": "warehouse",
      "name": "Kessler Parts Depot Lingen",
      "city": "Lingen",
      "lat": 52.5236,
      "lon": 7.3187,
      "available": 20,
      "pickup": false
    },
    {
      "id": "WH-003",
      "kind": "warehouse",
      "name": "Bakker Parts Depot Coevorden",
      "city": "Coevorden",
      "lat": 52.6606,
      "lon": 6.7411,
      "available": 9,
      "pickup": false
    },
    {
      "id": "WH-004",
      "kind": "warehouse",
      "name": "Regional Distribution Centre Zwolle",
      "city": "Zwolle",
      "lat": 52.5168,
      "lon": 6.083,
      "available": 11,
      "pickup": false
    }
  ],
  "customer": {
    "id": "CUS-008",
    "name": "Brabantia Warehousing",
    "city": "Eindhoven",
    "lat": 51.4416,
    "lon": 5.4697
  },
  "pickupDealer": "DLR-004",
  "delivery": {
    "from": "WH-004",
    "km": 164.7,
    "standard": {
      "price": 19.0,
      "days": 3
    },
    "express": {
      "price": 34.2,
      "days": 2
    }
  }
} as const
