// GENERATED by scripts/build-data.py from backend/data/catalogue/noordveld-parts-catalog.xlsx. Do not edit by hand.

export const catalogMachines = [
  {
    "model": "NV-2100",
    "machineType": "Skid Steer Loader",
    "plant": "Assen (NL)",
    "brandOrigin": "Noordveld"
  },
  {
    "model": "NV-3200",
    "machineType": "Compact Wheel Loader",
    "plant": "Assen (NL)",
    "brandOrigin": "Noordveld"
  },
  {
    "model": "NV-4500",
    "machineType": "Wheel Loader",
    "plant": "Assen (NL)",
    "brandOrigin": "Noordveld"
  },
  {
    "model": "NV-6000",
    "machineType": "Telehandler",
    "plant": "Assen (NL)",
    "brandOrigin": "Noordveld"
  },
  {
    "model": "NV-7500",
    "machineType": "Articulated Loader",
    "plant": "Assen (NL)",
    "brandOrigin": "Noordveld"
  },
  {
    "model": "KFT-120",
    "machineType": "Pallet Truck",
    "plant": "Lingen (DE)",
    "brandOrigin": "Kessler (acquired 2014)"
  },
  {
    "model": "KFT-200",
    "machineType": "Electric Forklift",
    "plant": "Lingen (DE)",
    "brandOrigin": "Kessler (acquired 2014)"
  },
  {
    "model": "KFT-450",
    "machineType": "Reach Truck",
    "plant": "Lingen (DE)",
    "brandOrigin": "Kessler (acquired 2014)"
  },
  {
    "model": "KFT-600",
    "machineType": "Loader Arm Unit",
    "plant": "Lingen (DE)",
    "brandOrigin": "Kessler (acquired 2014)"
  },
  {
    "model": "KFT-800",
    "machineType": "Stacker Crane",
    "plant": "Lingen (DE)",
    "brandOrigin": "Kessler (acquired 2014)"
  },
  {
    "model": "BTS-100",
    "machineType": "Belt Conveyor Module",
    "plant": "Coevorden (NL)",
    "brandOrigin": "Bakker (acquired 2019)"
  },
  {
    "model": "BTS-250",
    "machineType": "Loader Arm Assembly (machine)",
    "plant": "Coevorden (NL)",
    "brandOrigin": "Bakker (acquired 2019)"
  },
  {
    "model": "BTS-500",
    "machineType": "Roller Conveyor",
    "plant": "Coevorden (NL)",
    "brandOrigin": "Bakker (acquired 2019)"
  },
  {
    "model": "BTS-750",
    "machineType": "Transfer Cart",
    "plant": "Coevorden (NL)",
    "brandOrigin": "Bakker (acquired 2019)"
  },
  {
    "model": "BTS-900",
    "machineType": "Pallet Elevator",
    "plant": "Coevorden (NL)",
    "brandOrigin": "Bakker (acquired 2019)"
  }
] as const

export const catalogParts = [
  {
    "partNo": "NVM-4410-SK",
    "name": "Hydraulic seal kit, main lift cylinder",
    "category": "Hydraulics",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-600"
    ],
    "specNote": "Bore 63mm, NBR seals"
  },
  {
    "partNo": "NVM-1010-HY",
    "name": "Hydraulic hose, high-pressure 19mm",
    "category": "Hydraulics",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500"
    ],
    "specNote": "3/4 in, 2-wire braid, 900mm"
  },
  {
    "partNo": "NVM-1020-HY",
    "name": "Hydraulic hose, high-pressure 13mm",
    "category": "Hydraulics",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-2100",
      "NV-3200"
    ],
    "specNote": "1/2 in, 2-wire braid, 600mm"
  },
  {
    "partNo": "NVM-1030-HY",
    "name": "Main lift cylinder, double-acting",
    "category": "Hydraulics",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "Bore 100mm, stroke 850mm"
  },
  {
    "partNo": "NVM-1040-HY",
    "name": "Tilt cylinder, double-acting",
    "category": "Hydraulics",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500"
    ],
    "specNote": "Bore 80mm, stroke 400mm"
  },
  {
    "partNo": "NVM-1050-HY",
    "name": "Gear pump, 28cc/rev",
    "category": "Hydraulics",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-200",
      "KFT-450"
    ],
    "specNote": "Max 210 bar"
  },
  {
    "partNo": "NVM-1060-HY",
    "name": "Piston pump, variable displacement",
    "category": "Hydraulics",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-600",
      "KFT-800"
    ],
    "specNote": "45cc/rev, load-sensing"
  },
  {
    "partNo": "NVM-1070-HY",
    "name": "Directional control valve, 4-spool",
    "category": "Hydraulics",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "Open-centre, 80 L/min"
  },
  {
    "partNo": "NVM-1080-HY",
    "name": "Relief valve, 210 bar",
    "category": "Hydraulics",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "Cartridge type"
  },
  {
    "partNo": "NVM-1090-HY",
    "name": "Hydraulic filter housing, return line",
    "category": "Hydraulics",
    "plantOfOrigin": "Coevorden (NL)",
    "compatibleModels": [
      "BTS-250",
      "BTS-750"
    ],
    "specNote": "10 micron element"
  },
  {
    "partNo": "NVM-1100-HY",
    "name": "Quick-release coupling set, ISO 7241-1",
    "category": "Hydraulics",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "1/2 in BSP"
  },
  {
    "partNo": "NVM-1110-HY",
    "name": "Hydraulic reservoir tank, 60L",
    "category": "Hydraulics",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-600",
      "KFT-800"
    ],
    "specNote": "Steel, baffled"
  },
  {
    "partNo": "NVM-1120-HY",
    "name": "Tilt cylinder seal kit",
    "category": "Hydraulics",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500"
    ],
    "specNote": "Viton seals, high-temp"
  },
  {
    "partNo": "NVM-1130-HY",
    "name": "Boom cylinder pin bushing set",
    "category": "Hydraulics",
    "plantOfOrigin": "Coevorden (NL)",
    "compatibleModels": [
      "BTS-250"
    ],
    "specNote": "Bronze, 45mm bore"
  },
  {
    "partNo": "NVM-1140-HY",
    "name": "Hydraulic oil cooler, air-to-oil",
    "category": "Hydraulics",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "12V fan, 40L/min rated"
  },
  {
    "partNo": "NVM-2210-GX",
    "name": "Gearbox output sprocket, 24-tooth",
    "category": "Drivetrain",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "3/4 in pitch, bore 32mm"
  },
  {
    "partNo": "NVM-1010-DT",
    "name": "Drive chain, roller, 3/4 in pitch",
    "category": "Drivetrain",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "ANSI 60, 5m coil"
  },
  {
    "partNo": "NVM-1020-DT",
    "name": "Final drive gearbox assembly",
    "category": "Drivetrain",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-600",
      "KFT-800"
    ],
    "specNote": "Ratio 18.5:1"
  },
  {
    "partNo": "NVM-1030-DT",
    "name": "Axle shaft, front, splined",
    "category": "Drivetrain",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500"
    ],
    "specNote": "28-spline, 850mm"
  },
  {
    "partNo": "NVM-1040-DT",
    "name": "Axle shaft, rear, splined",
    "category": "Drivetrain",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500"
    ],
    "specNote": "28-spline, 820mm"
  },
  {
    "partNo": "NVM-1050-DT",
    "name": "Differential gear set, 4.1:1 ratio",
    "category": "Drivetrain",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "Limited-slip option"
  },
  {
    "partNo": "NVM-1060-DT",
    "name": "Wheel hub bearing, tapered roller",
    "category": "Drivetrain",
    "plantOfOrigin": "Coevorden (NL)",
    "compatibleModels": [
      "BTS-750",
      "BTS-900"
    ],
    "specNote": "Double row, sealed"
  },
  {
    "partNo": "NVM-1070-DT",
    "name": "Transfer case coupling",
    "category": "Drivetrain",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-600"
    ],
    "specNote": "Splined, 40mm"
  },
  {
    "partNo": "NVM-1080-DT",
    "name": "Drive belt, poly-V, 6-rib",
    "category": "Drivetrain",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-2100",
      "NV-3200"
    ],
    "specNote": "1850mm effective length"
  },
  {
    "partNo": "NVM-1090-DT",
    "name": "Clutch plate assembly",
    "category": "Drivetrain",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-200",
      "KFT-450"
    ],
    "specNote": "Wet clutch, 8 plate"
  },
  {
    "partNo": "NVM-1100-DT",
    "name": "Universal joint, heavy duty",
    "category": "Drivetrain",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "Series 1350"
  },
  {
    "partNo": "NVM-1110-DT",
    "name": "Planetary gear carrier",
    "category": "Drivetrain",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-600",
      "KFT-800"
    ],
    "specNote": "3-planet, hardened steel"
  },
  {
    "partNo": "NVM-1120-DT",
    "name": "Output shaft seal",
    "category": "Drivetrain",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "45mm ID, dual lip"
  },
  {
    "partNo": "NVM-1130-DT",
    "name": "Wheel rim, 16-inch, 8-bolt",
    "category": "Drivetrain",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "Steel, 8x275 PCD"
  },
  {
    "partNo": "NVM-1140-DT",
    "name": "Track roller assembly",
    "category": "Drivetrain",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-7500"
    ],
    "specNote": "For tracked NV-7500 variant"
  },
  {
    "partNo": "NVM-1010-EL",
    "name": "Wiring harness, main chassis",
    "category": "Electrical",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "CAN-bus, 2.1m"
  },
  {
    "partNo": "NVM-1020-EL",
    "name": "Ignition switch assembly",
    "category": "Electrical",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-2100",
      "NV-3200",
      "NV-4500"
    ],
    "specNote": "4-position, keyed"
  },
  {
    "partNo": "NVM-1030-EL",
    "name": "Proximity sensor, boom position",
    "category": "Electrical",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-600",
      "KFT-800"
    ],
    "specNote": "Inductive, 10mm range"
  },
  {
    "partNo": "NVM-1040-EL",
    "name": "Load sensor, hydraulic pressure transducer",
    "category": "Electrical",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-200",
      "KFT-450"
    ],
    "specNote": "0-350 bar, 4-20mA out"
  },
  {
    "partNo": "NVM-1050-EL",
    "name": "Control module, main ECU",
    "category": "Electrical",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "CAN J1939"
  },
  {
    "partNo": "NVM-1060-EL",
    "name": "Joystick controller assembly",
    "category": "Electrical",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "2-axis, proportional"
  },
  {
    "partNo": "NVM-1070-EL",
    "name": "Battery, 12V 100Ah",
    "category": "Electrical",
    "plantOfOrigin": "Coevorden (NL)",
    "compatibleModels": [
      "BTS-750",
      "BTS-900"
    ],
    "specNote": "AGM, group 31"
  },
  {
    "partNo": "NVM-1080-EL",
    "name": "Alternator, 90A",
    "category": "Electrical",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500"
    ],
    "specNote": "12V, fan-cooled"
  },
  {
    "partNo": "NVM-1090-EL",
    "name": "Starter motor",
    "category": "Electrical",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "12V, 2.2kW"
  },
  {
    "partNo": "NVM-1100-EL",
    "name": "Headlight assembly, LED",
    "category": "Electrical",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-2100",
      "NV-3200"
    ],
    "specNote": "Left/right pair"
  },
  {
    "partNo": "NVM-1110-EL",
    "name": "Warning beacon, amber rotating",
    "category": "Electrical",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-200",
      "KFT-450",
      "KFT-800"
    ],
    "specNote": "12/24V, magnetic base"
  },
  {
    "partNo": "NVM-1120-EL",
    "name": "Instrument cluster display",
    "category": "Electrical",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "5in, sunlight readable"
  },
  {
    "partNo": "NVM-2205-BH",
    "name": "Bearing housing, front axle",
    "category": "Structural",
    "plantOfOrigin": "Coevorden (NL)",
    "compatibleModels": [
      "BTS-250"
    ],
    "specNote": "Cast iron, matched to AS-650 series"
  },
  {
    "partNo": "NVM-1010-ST",
    "name": "Loader arm assembly, left",
    "category": "Structural",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-600",
      "BTS-250"
    ],
    "specNote": "Forged steel, cross-compatible after 2019 unification"
  },
  {
    "partNo": "NVM-1020-ST",
    "name": "Loader arm assembly, right",
    "category": "Structural",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-600",
      "BTS-250"
    ],
    "specNote": "Forged steel, cross-compatible after 2019 unification"
  },
  {
    "partNo": "NVM-1030-ST",
    "name": "Boom pivot pin",
    "category": "Structural",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "50mm dia, hardened"
  },
  {
    "partNo": "NVM-1040-ST",
    "name": "Boom pivot bushing",
    "category": "Structural",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "Bronze-lined"
  },
  {
    "partNo": "NVM-1050-ST",
    "name": "Frame crossmember",
    "category": "Structural",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "Bolt-in, galvanised"
  },
  {
    "partNo": "NVM-1060-ST",
    "name": "Counterweight bracket",
    "category": "Structural",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "Rated 450kg"
  },
  {
    "partNo": "NVM-1070-ST",
    "name": "Cab mounting bracket",
    "category": "Structural",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "Rubber-isolated"
  },
  {
    "partNo": "NVM-1080-ST",
    "name": "Chassis tie rod",
    "category": "Structural",
    "plantOfOrigin": "Coevorden (NL)",
    "compatibleModels": [
      "BTS-100",
      "BTS-500"
    ],
    "specNote": "Adjustable, M24 thread"
  },
  {
    "partNo": "NVM-1090-ST",
    "name": "Lift arm linkage plate",
    "category": "Structural",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-600",
      "KFT-800"
    ],
    "specNote": "12mm plate steel"
  },
  {
    "partNo": "NVM-1100-ST",
    "name": "Bucket pivot pin",
    "category": "Structural",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500"
    ],
    "specNote": "40mm dia"
  },
  {
    "partNo": "NVM-1110-ST",
    "name": "Stabilizer leg assembly",
    "category": "Structural",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-6000"
    ],
    "specNote": "Hydraulic, single-acting"
  },
  {
    "partNo": "NVM-1120-ST",
    "name": "Tow hitch bracket",
    "category": "Structural",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-2100",
      "NV-3200",
      "NV-4500"
    ],
    "specNote": "Pin-and-clevis type"
  },
  {
    "partNo": "NVM-1130-ST",
    "name": "Engine mount bushing",
    "category": "Structural",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500"
    ],
    "specNote": "Rubber, vibration-damped"
  },
  {
    "partNo": "NVM-1140-ST",
    "name": "Footstep bracket, operator platform",
    "category": "Structural",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-2100",
      "NV-3200"
    ],
    "specNote": "Non-slip tread"
  },
  {
    "partNo": "NVM-1010-FL",
    "name": "Air filter, primary",
    "category": "Filtration",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "Radial seal"
  },
  {
    "partNo": "NVM-1020-FL",
    "name": "Air filter, secondary/safety",
    "category": "Filtration",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "Fits inside AS-910 housing"
  },
  {
    "partNo": "NVM-1030-FL",
    "name": "Fuel filter, inline",
    "category": "Filtration",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "10 micron"
  },
  {
    "partNo": "NVM-1040-FL",
    "name": "Fuel filter, primary/water separator",
    "category": "Filtration",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "With drain valve"
  },
  {
    "partNo": "NVM-1050-FL",
    "name": "Engine oil filter",
    "category": "Filtration",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500",
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "Spin-on"
  },
  {
    "partNo": "NVM-1060-FL",
    "name": "Hydraulic return filter element",
    "category": "Filtration",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-600",
      "KFT-800"
    ],
    "specNote": "10 micron, beta 75"
  },
  {
    "partNo": "NVM-1070-FL",
    "name": "Cabin air filter",
    "category": "Filtration",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "Activated carbon"
  },
  {
    "partNo": "NVM-1080-FL",
    "name": "Transmission filter element",
    "category": "Filtration",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-200",
      "KFT-450"
    ],
    "specNote": "Spin-on, 20 micron"
  },
  {
    "partNo": "NVM-1010-BR",
    "name": "Brake pad set, front",
    "category": "Brakes",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500"
    ],
    "specNote": "Semi-metallic"
  },
  {
    "partNo": "NVM-1020-BR",
    "name": "Brake pad set, rear",
    "category": "Brakes",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500"
    ],
    "specNote": "Semi-metallic"
  },
  {
    "partNo": "NVM-1030-BR",
    "name": "Brake disc, front",
    "category": "Brakes",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "Vented, 280mm"
  },
  {
    "partNo": "NVM-1040-BR",
    "name": "Brake disc, rear",
    "category": "Brakes",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "Solid, 260mm"
  },
  {
    "partNo": "NVM-1050-BR",
    "name": "Brake caliper assembly",
    "category": "Brakes",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "Twin-piston"
  },
  {
    "partNo": "NVM-1060-BR",
    "name": "Parking brake cable",
    "category": "Brakes",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-200",
      "KFT-450"
    ],
    "specNote": "1.8m, manual lever type"
  },
  {
    "partNo": "NVM-1070-BR",
    "name": "Brake fluid reservoir",
    "category": "Brakes",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "DOT 4"
  },
  {
    "partNo": "NVM-1080-BR",
    "name": "Brake master cylinder",
    "category": "Brakes",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "22mm bore"
  },
  {
    "partNo": "NVM-1010-CL",
    "name": "Radiator assembly",
    "category": "Cooling",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "Aluminium, cross-flow"
  },
  {
    "partNo": "NVM-1020-CL",
    "name": "Cooling fan, engine-driven",
    "category": "Cooling",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "9-blade, viscous clutch"
  },
  {
    "partNo": "NVM-1030-CL",
    "name": "Fan belt",
    "category": "Cooling",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500"
    ],
    "specNote": "1600mm, poly-V"
  },
  {
    "partNo": "NVM-1040-CL",
    "name": "Thermostat housing",
    "category": "Cooling",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-600",
      "KFT-800"
    ],
    "specNote": "82C opening"
  },
  {
    "partNo": "NVM-1050-CL",
    "name": "Water pump",
    "category": "Cooling",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "Belt-driven"
  },
  {
    "partNo": "NVM-1060-CL",
    "name": "Coolant hose set",
    "category": "Cooling",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "Upper and lower, silicone"
  },
  {
    "partNo": "NVM-1010-CB",
    "name": "Operator seat, suspension type",
    "category": "Cab & Controls",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "Air suspension, armrests"
  },
  {
    "partNo": "NVM-1020-CB",
    "name": "Seat belt assembly",
    "category": "Cab & Controls",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-2100",
      "NV-3200",
      "NV-4500",
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "Retractable, 2-point"
  },
  {
    "partNo": "NVM-1030-CB",
    "name": "Steering wheel",
    "category": "Cab & Controls",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "350mm, polyurethane rim"
  },
  {
    "partNo": "NVM-1040-CB",
    "name": "Steering column assembly",
    "category": "Cab & Controls",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "Tilt-adjustable"
  },
  {
    "partNo": "NVM-1050-CB",
    "name": "Wiper motor assembly",
    "category": "Cab & Controls",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-600",
      "KFT-800"
    ],
    "specNote": "12V, 2-speed"
  },
  {
    "partNo": "NVM-1060-CB",
    "name": "Cab door glass, left",
    "category": "Cab & Controls",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "Tempered, tinted"
  },
  {
    "partNo": "NVM-1070-CB",
    "name": "Cab door glass, right",
    "category": "Cab & Controls",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "Tempered, tinted"
  },
  {
    "partNo": "NVM-1080-CB",
    "name": "HVAC blower motor",
    "category": "Cab & Controls",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "12V, 3-speed"
  },
  {
    "partNo": "NVM-1010-AT",
    "name": "Bucket, general purpose, 1.2m3",
    "category": "Attachments",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "Bolt-on cutting edge"
  },
  {
    "partNo": "NVM-1020-AT",
    "name": "Bucket, high-tip, 1.0m3",
    "category": "Attachments",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500"
    ],
    "specNote": "Extended dump height"
  },
  {
    "partNo": "NVM-1030-AT",
    "name": "Fork set, pallet, 1200mm",
    "category": "Attachments",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-200",
      "KFT-450"
    ],
    "specNote": "Class II carriage"
  },
  {
    "partNo": "NVM-1040-AT",
    "name": "Tine, bale spike",
    "category": "Attachments",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "Single spike, 900mm"
  },
  {
    "partNo": "NVM-1050-AT",
    "name": "Quick-coupler plate",
    "category": "Attachments",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "Hydraulic lock"
  },
  {
    "partNo": "NVM-1060-AT",
    "name": "Grapple attachment",
    "category": "Attachments",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "Rotating, hydraulic"
  },
  {
    "partNo": "NVM-1070-AT",
    "name": "Sweeper brush attachment",
    "category": "Attachments",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500"
    ],
    "specNote": "1.8m width"
  },
  {
    "partNo": "NVM-1080-AT",
    "name": "Snow blade, 2.4m",
    "category": "Attachments",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "Angling, hydraulic"
  },
  {
    "partNo": "NVM-1010-LU",
    "name": "Grease nipple set",
    "category": "Lubrication",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500",
      "NV-6000",
      "NV-7500"
    ],
    "specNote": "Assorted, M8/M10"
  },
  {
    "partNo": "NVM-1020-LU",
    "name": "Central lubrication pump",
    "category": "Lubrication",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-600",
      "KFT-800"
    ],
    "specNote": "Electric, 2L reservoir"
  },
  {
    "partNo": "NVM-1030-LU",
    "name": "Grease line hose kit",
    "category": "Lubrication",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "6mm nylon tube"
  },
  {
    "partNo": "NVM-1040-LU",
    "name": "Oil dipstick assembly",
    "category": "Lubrication",
    "plantOfOrigin": "Assen (NL)",
    "compatibleModels": [
      "NV-3200",
      "NV-4500",
      "NV-6000"
    ],
    "specNote": "Engine, marked H/L"
  },
  {
    "partNo": "NVM-1050-LU",
    "name": "Auto-lube reservoir, 4L",
    "category": "Lubrication",
    "plantOfOrigin": "Lingen (DE)",
    "compatibleModels": [
      "KFT-800"
    ],
    "specNote": "For stacker crane mast"
  }
] as const
