// Noordveld Parts Intelligence graph. GENERATED by scripts/graph_build.py on 2026-10-03; do not edit by hand.
// Idempotent: MERGE on canonical ids and rel_id, so running it again creates nothing new.
// Source: noordveld-complete-dataset-synthetic-demo.xlsx. Synthetic records carry data_status = 'SYNTHETIC_DEMO'.

// Read-only validation. Each query is followed by its expected result in validation_expected_results.md.

// V01 Total nodes
// expected: 1840
MATCH (n) RETURN count(n) AS nodes;

// V02 Total relationships
// expected: 3812
MATCH ()-[r]->() RETURN count(r) AS relationships;

// V03 Nodes per label
// expected: Address 44, Assembly 15, BusinessUnit 3, Carrier 1, Cart 3, CartLine 6, Category 101, ComplianceRequirement 8, Customer 10, DataSource 4, Dealer 15, DeliveryEstimate 100, IdentificationRequirement 6, LegacyReference 100, Location 5, Machine 15, MachineFamily 3, MachineSpecification 83, MachineType 15, MachineVariant 30, Order 8, OrderLine 14, OrderStatus 6, OrderStatusEvent 32, Part 100, PartCatalogProfile 100, PartSpecification 279, Plant 3, Price 100, Region 14, SearchAlias 493, ServicePlan 60, Shipment 9, ShippingRate 8, Supplier 12, SupplierBackorder 4, TrackingEvent 27, Warehouse 4
MATCH (n) UNWIND labels(n) AS label RETURN label, count(*) AS nodes ORDER BY label;

// V04 Relationships per type
// expected: ADMITS_VARIANT 10, ALLOCATED_FROM 10, AVAILABLE_AT 400, BRANDED_AS 15, CARRIED_BY 9, CONTAINS_LINE 20, COVERS_CATEGORY 10, CO_ORDERED_WITH 75, DELIVERS_TO_ADDRESS 8, DELIVERS_TO_CUSTOMER 9, DISPATCHED_FROM 9, FITS 219, FOR_MACHINE 66, FOR_PART 10, FROM_WAREHOUSE 100, HAS_ALIAS 493, HAS_COMPLIANCE 100, HAS_LEGACY_REFERENCE 100, HAS_MACHINE_SPECIFICATION 83, HAS_SHIPMENT 9, HAS_SPECIFICATION 279, HAS_STATUS_EVENT 32, HAS_TRACKING_EVENT 27, HOME_PLANT 3, IDENTIFIED_BY_PART 15, IN_CATEGORY 100, IN_COUNTRY 3, IN_REGION 44, IN_SUBCATEGORY 100, ISSUED_BY_BUSINESS_UNIT 100, LOCATED_AT_ADDRESS 44, LOCATED_AT_PLANT 3, LOCATED_IN 3, MANUFACTURED_AT 15, MEMBER_OF_FAMILY 15, OF_TYPE 15, OPENED_BY 3, ORDERED_BY 8, ORIGINATES_AT 100, OWNED_BY 3, PART_OF 35, PLACED_WITH 4, PLANNED_FULFILMENT_FROM 4, PRICES_PART 100, PRODUCT_FAMILY_OF 3, PROFILES_PART 100, RECORDS_STATUS 32, REFERENCES_PART 20, RELATED_COMPONENT 2, REQUIRES_PART 71, SAME_NAME_GROUP_AS 9, SERVES_FAMILY 30, SHIPS_LINE 9, SHIPS_TO_COUNTRY 8, STOCKED_BY 315, SUBCATEGORY_OF 91, SUPPLIED_BY 157, SUPPLIES_CATEGORY 25, TO_CUSTOMER 40, TO_DEALER 60, VARIANT_OF 30
MATCH ()-[r]->() RETURN type(r) AS type, count(*) AS relationships ORDER BY type;

// V05 Nodes and relationships per data_status
// expected: node DERIVED 165, node SOURCE_DERIVED 456, node SYNTHETIC_DEMO 1209, node USER_PROVIDED 10; relationship DERIVED 391, relationship SOURCE_DERIVED 778, relationship SYNTHETIC_DEMO 2637, relationship USER_PROVIDED 6
MATCH (n) RETURN 'node' AS kind, n.data_status AS status, count(*) AS c UNION ALL MATCH ()-[r]->() RETURN 'relationship' AS kind, r.data_status AS status, count(*) AS c;

// V06 Duplicate canonical ids (any label)
// expected: 0 rows
MATCH (n:Address) WITH n.address_id AS id, count(*) AS c WHERE c > 1 RETURN 'Address' AS label, id, c UNION ALL
MATCH (n:Assembly) WITH n.assembly_id AS id, count(*) AS c WHERE c > 1 RETURN 'Assembly' AS label, id, c UNION ALL
MATCH (n:BusinessUnit) WITH n.business_unit_id AS id, count(*) AS c WHERE c > 1 RETURN 'BusinessUnit' AS label, id, c UNION ALL
MATCH (n:Carrier) WITH n.carrier_id AS id, count(*) AS c WHERE c > 1 RETURN 'Carrier' AS label, id, c UNION ALL
MATCH (n:Cart) WITH n.cart_id AS id, count(*) AS c WHERE c > 1 RETURN 'Cart' AS label, id, c UNION ALL
MATCH (n:CartLine) WITH n.cart_line_id AS id, count(*) AS c WHERE c > 1 RETURN 'CartLine' AS label, id, c UNION ALL
MATCH (n:Category) WITH n.category_id AS id, count(*) AS c WHERE c > 1 RETURN 'Category' AS label, id, c UNION ALL
MATCH (n:ComplianceRequirement) WITH n.compliance_id AS id, count(*) AS c WHERE c > 1 RETURN 'ComplianceRequirement' AS label, id, c UNION ALL
MATCH (n:Customer) WITH n.customer_id AS id, count(*) AS c WHERE c > 1 RETURN 'Customer' AS label, id, c UNION ALL
MATCH (n:DataSource) WITH n.source_id AS id, count(*) AS c WHERE c > 1 RETURN 'DataSource' AS label, id, c UNION ALL
MATCH (n:Dealer) WITH n.dealer_id AS id, count(*) AS c WHERE c > 1 RETURN 'Dealer' AS label, id, c UNION ALL
MATCH (n:DeliveryEstimate) WITH n.delivery_estimate_id AS id, count(*) AS c WHERE c > 1 RETURN 'DeliveryEstimate' AS label, id, c UNION ALL
MATCH (n:IdentificationRequirement) WITH n.requirement_id AS id, count(*) AS c WHERE c > 1 RETURN 'IdentificationRequirement' AS label, id, c UNION ALL
MATCH (n:LegacyReference) WITH n.legacy_reference_id AS id, count(*) AS c WHERE c > 1 RETURN 'LegacyReference' AS label, id, c UNION ALL
MATCH (n:Location) WITH n.location_id AS id, count(*) AS c WHERE c > 1 RETURN 'Location' AS label, id, c UNION ALL
MATCH (n:Machine) WITH n.machine_id AS id, count(*) AS c WHERE c > 1 RETURN 'Machine' AS label, id, c UNION ALL
MATCH (n:MachineFamily) WITH n.family_id AS id, count(*) AS c WHERE c > 1 RETURN 'MachineFamily' AS label, id, c UNION ALL
MATCH (n:MachineSpecification) WITH n.machine_spec_id AS id, count(*) AS c WHERE c > 1 RETURN 'MachineSpecification' AS label, id, c UNION ALL
MATCH (n:MachineType) WITH n.machine_type_id AS id, count(*) AS c WHERE c > 1 RETURN 'MachineType' AS label, id, c UNION ALL
MATCH (n:MachineVariant) WITH n.variant_id AS id, count(*) AS c WHERE c > 1 RETURN 'MachineVariant' AS label, id, c UNION ALL
MATCH (n:Order) WITH n.order_id AS id, count(*) AS c WHERE c > 1 RETURN 'Order' AS label, id, c UNION ALL
MATCH (n:OrderLine) WITH n.order_line_id AS id, count(*) AS c WHERE c > 1 RETURN 'OrderLine' AS label, id, c UNION ALL
MATCH (n:OrderStatus) WITH n.order_status_code AS id, count(*) AS c WHERE c > 1 RETURN 'OrderStatus' AS label, id, c UNION ALL
MATCH (n:OrderStatusEvent) WITH n.status_event_id AS id, count(*) AS c WHERE c > 1 RETURN 'OrderStatusEvent' AS label, id, c UNION ALL
MATCH (n:Part) WITH n.part_id AS id, count(*) AS c WHERE c > 1 RETURN 'Part' AS label, id, c UNION ALL
MATCH (n:PartCatalogProfile) WITH n.profile_id AS id, count(*) AS c WHERE c > 1 RETURN 'PartCatalogProfile' AS label, id, c UNION ALL
MATCH (n:PartSpecification) WITH n.specification_id AS id, count(*) AS c WHERE c > 1 RETURN 'PartSpecification' AS label, id, c UNION ALL
MATCH (n:Plant) WITH n.plant_id AS id, count(*) AS c WHERE c > 1 RETURN 'Plant' AS label, id, c UNION ALL
MATCH (n:Price) WITH n.price_id AS id, count(*) AS c WHERE c > 1 RETURN 'Price' AS label, id, c UNION ALL
MATCH (n:Region) WITH n.region_id AS id, count(*) AS c WHERE c > 1 RETURN 'Region' AS label, id, c UNION ALL
MATCH (n:SearchAlias) WITH n.alias_id AS id, count(*) AS c WHERE c > 1 RETURN 'SearchAlias' AS label, id, c UNION ALL
MATCH (n:ServicePlan) WITH n.service_plan_id AS id, count(*) AS c WHERE c > 1 RETURN 'ServicePlan' AS label, id, c UNION ALL
MATCH (n:Shipment) WITH n.shipment_id AS id, count(*) AS c WHERE c > 1 RETURN 'Shipment' AS label, id, c UNION ALL
MATCH (n:ShippingRate) WITH n.rate_id AS id, count(*) AS c WHERE c > 1 RETURN 'ShippingRate' AS label, id, c UNION ALL
MATCH (n:Supplier) WITH n.supplier_id AS id, count(*) AS c WHERE c > 1 RETURN 'Supplier' AS label, id, c UNION ALL
MATCH (n:SupplierBackorder) WITH n.backorder_id AS id, count(*) AS c WHERE c > 1 RETURN 'SupplierBackorder' AS label, id, c UNION ALL
MATCH (n:TrackingEvent) WITH n.tracking_event_id AS id, count(*) AS c WHERE c > 1 RETURN 'TrackingEvent' AS label, id, c UNION ALL
MATCH (n:Warehouse) WITH n.warehouse_id AS id, count(*) AS c WHERE c > 1 RETURN 'Warehouse' AS label, id, c;

// V07 Duplicate relationships (same type, same endpoints, same rel_id)
// expected: 0 rows
MATCH (a)-[r]->(b) WITH type(r) AS t, r.rel_id AS id, count(*) AS c WHERE c > 1 RETURN t, id, c;

// V08 Nodes or relationships without provenance
// expected: node 0, relationship 0
MATCH (n) WHERE n.data_status IS NULL OR n.source_sheet IS NULL WITH count(n) AS c RETURN 'node' AS kind, c UNION ALL MATCH ()-[r]->() WHERE r.data_status IS NULL OR r.source_sheet IS NULL WITH count(r) AS c RETURN 'relationship' AS kind, c;

// V09 Synthetic sheets not marked SYNTHETIC_DEMO
// expected: 0
MATCH (n) WHERE n.source_sheet STARTS WITH 'SYN_' AND n.data_status <> 'SYNTHETIC_DEMO' RETURN count(n) AS nodes_unmarked;

// V10 Relationships with a wrong endpoint label
// expected: one row per relationship type (61), bad = 0 in every row
MATCH (a)-[r:ADMITS_VARIANT]->(b) WHERE NOT ((a:IdentificationRequirement AND b:MachineVariant)) WITH count(r) AS bad RETURN 'ADMITS_VARIANT' AS type, bad UNION ALL
MATCH (a)-[r:ALLOCATED_FROM]->(b) WHERE NOT ((a:OrderLine AND b:Warehouse)) WITH count(r) AS bad RETURN 'ALLOCATED_FROM' AS type, bad UNION ALL
MATCH (a)-[r:AVAILABLE_AT]->(b) WHERE NOT ((a:Part AND b:Warehouse)) WITH count(r) AS bad RETURN 'AVAILABLE_AT' AS type, bad UNION ALL
MATCH (a)-[r:BRANDED_AS]->(b) WHERE NOT ((a:Machine AND b:BusinessUnit)) WITH count(r) AS bad RETURN 'BRANDED_AS' AS type, bad UNION ALL
MATCH (a)-[r:CARRIED_BY]->(b) WHERE NOT ((a:Shipment AND b:Carrier)) WITH count(r) AS bad RETURN 'CARRIED_BY' AS type, bad UNION ALL
MATCH (a)-[r:CONTAINS_LINE]->(b) WHERE NOT ((a:Cart AND b:CartLine) OR (a:Order AND b:OrderLine)) WITH count(r) AS bad RETURN 'CONTAINS_LINE' AS type, bad UNION ALL
MATCH (a)-[r:COVERS_CATEGORY]->(b) WHERE NOT ((a:ComplianceRequirement AND b:Category)) WITH count(r) AS bad RETURN 'COVERS_CATEGORY' AS type, bad UNION ALL
MATCH (a)-[r:CO_ORDERED_WITH]->(b) WHERE NOT ((a:Part AND b:Part)) WITH count(r) AS bad RETURN 'CO_ORDERED_WITH' AS type, bad UNION ALL
MATCH (a)-[r:DELIVERS_TO_ADDRESS]->(b) WHERE NOT ((a:Order AND b:Address)) WITH count(r) AS bad RETURN 'DELIVERS_TO_ADDRESS' AS type, bad UNION ALL
MATCH (a)-[r:DELIVERS_TO_CUSTOMER]->(b) WHERE NOT ((a:Shipment AND b:Customer)) WITH count(r) AS bad RETURN 'DELIVERS_TO_CUSTOMER' AS type, bad UNION ALL
MATCH (a)-[r:DISPATCHED_FROM]->(b) WHERE NOT ((a:Shipment AND b:Warehouse)) WITH count(r) AS bad RETURN 'DISPATCHED_FROM' AS type, bad UNION ALL
MATCH (a)-[r:FITS]->(b) WHERE NOT ((a:Part AND b:Machine)) WITH count(r) AS bad RETURN 'FITS' AS type, bad UNION ALL
MATCH (a)-[r:FOR_MACHINE]->(b) WHERE NOT ((a:IdentificationRequirement AND b:Machine) OR (a:ServicePlan AND b:Machine)) WITH count(r) AS bad RETURN 'FOR_MACHINE' AS type, bad UNION ALL
MATCH (a)-[r:FOR_PART]->(b) WHERE NOT ((a:SupplierBackorder AND b:Part) OR (a:IdentificationRequirement AND b:Part)) WITH count(r) AS bad RETURN 'FOR_PART' AS type, bad UNION ALL
MATCH (a)-[r:FROM_WAREHOUSE]->(b) WHERE NOT ((a:DeliveryEstimate AND b:Warehouse)) WITH count(r) AS bad RETURN 'FROM_WAREHOUSE' AS type, bad UNION ALL
MATCH (a)-[r:HAS_ALIAS]->(b) WHERE NOT ((a:Part AND b:SearchAlias) OR (a:Machine AND b:SearchAlias)) WITH count(r) AS bad RETURN 'HAS_ALIAS' AS type, bad UNION ALL
MATCH (a)-[r:HAS_COMPLIANCE]->(b) WHERE NOT ((a:Part AND b:ComplianceRequirement)) WITH count(r) AS bad RETURN 'HAS_COMPLIANCE' AS type, bad UNION ALL
MATCH (a)-[r:HAS_LEGACY_REFERENCE]->(b) WHERE NOT ((a:Part AND b:LegacyReference)) WITH count(r) AS bad RETURN 'HAS_LEGACY_REFERENCE' AS type, bad UNION ALL
MATCH (a)-[r:HAS_MACHINE_SPECIFICATION]->(b) WHERE NOT ((a:Machine AND b:MachineSpecification)) WITH count(r) AS bad RETURN 'HAS_MACHINE_SPECIFICATION' AS type, bad UNION ALL
MATCH (a)-[r:HAS_SHIPMENT]->(b) WHERE NOT ((a:Order AND b:Shipment)) WITH count(r) AS bad RETURN 'HAS_SHIPMENT' AS type, bad UNION ALL
MATCH (a)-[r:HAS_SPECIFICATION]->(b) WHERE NOT ((a:Part AND b:PartSpecification)) WITH count(r) AS bad RETURN 'HAS_SPECIFICATION' AS type, bad UNION ALL
MATCH (a)-[r:HAS_STATUS_EVENT]->(b) WHERE NOT ((a:Order AND b:OrderStatusEvent)) WITH count(r) AS bad RETURN 'HAS_STATUS_EVENT' AS type, bad UNION ALL
MATCH (a)-[r:HAS_TRACKING_EVENT]->(b) WHERE NOT ((a:Shipment AND b:TrackingEvent)) WITH count(r) AS bad RETURN 'HAS_TRACKING_EVENT' AS type, bad UNION ALL
MATCH (a)-[r:HOME_PLANT]->(b) WHERE NOT ((a:BusinessUnit AND b:Plant)) WITH count(r) AS bad RETURN 'HOME_PLANT' AS type, bad UNION ALL
MATCH (a)-[r:IDENTIFIED_BY_PART]->(b) WHERE NOT ((a:Assembly AND b:Part)) WITH count(r) AS bad RETURN 'IDENTIFIED_BY_PART' AS type, bad UNION ALL
MATCH (a)-[r:IN_CATEGORY]->(b) WHERE NOT ((a:Part AND b:Category)) WITH count(r) AS bad RETURN 'IN_CATEGORY' AS type, bad UNION ALL
MATCH (a)-[r:IN_COUNTRY]->(b) WHERE NOT ((a:Location AND b:Location)) WITH count(r) AS bad RETURN 'IN_COUNTRY' AS type, bad UNION ALL
MATCH (a)-[r:IN_REGION]->(b) WHERE NOT ((a:Address AND b:Region)) WITH count(r) AS bad RETURN 'IN_REGION' AS type, bad UNION ALL
MATCH (a)-[r:IN_SUBCATEGORY]->(b) WHERE NOT ((a:Part AND b:Category)) WITH count(r) AS bad RETURN 'IN_SUBCATEGORY' AS type, bad UNION ALL
MATCH (a)-[r:ISSUED_BY_BUSINESS_UNIT]->(b) WHERE NOT ((a:LegacyReference AND b:BusinessUnit)) WITH count(r) AS bad RETURN 'ISSUED_BY_BUSINESS_UNIT' AS type, bad UNION ALL
MATCH (a)-[r:LOCATED_AT_ADDRESS]->(b) WHERE NOT ((a:Warehouse AND b:Address) OR (a:Supplier AND b:Address) OR (a:Dealer AND b:Address) OR (a:Customer AND b:Address) OR (a:Plant AND b:Address)) WITH count(r) AS bad RETURN 'LOCATED_AT_ADDRESS' AS type, bad UNION ALL
MATCH (a)-[r:LOCATED_AT_PLANT]->(b) WHERE NOT ((a:Warehouse AND b:Plant)) WITH count(r) AS bad RETURN 'LOCATED_AT_PLANT' AS type, bad UNION ALL
MATCH (a)-[r:LOCATED_IN]->(b) WHERE NOT ((a:Plant AND b:Location)) WITH count(r) AS bad RETURN 'LOCATED_IN' AS type, bad UNION ALL
MATCH (a)-[r:MANUFACTURED_AT]->(b) WHERE NOT ((a:Machine AND b:Plant)) WITH count(r) AS bad RETURN 'MANUFACTURED_AT' AS type, bad UNION ALL
MATCH (a)-[r:MEMBER_OF_FAMILY]->(b) WHERE NOT ((a:Machine AND b:MachineFamily)) WITH count(r) AS bad RETURN 'MEMBER_OF_FAMILY' AS type, bad UNION ALL
MATCH (a)-[r:OF_TYPE]->(b) WHERE NOT ((a:Machine AND b:MachineType)) WITH count(r) AS bad RETURN 'OF_TYPE' AS type, bad UNION ALL
MATCH (a)-[r:OPENED_BY]->(b) WHERE NOT ((a:Cart AND b:Customer)) WITH count(r) AS bad RETURN 'OPENED_BY' AS type, bad UNION ALL
MATCH (a)-[r:ORDERED_BY]->(b) WHERE NOT ((a:Order AND b:Customer)) WITH count(r) AS bad RETURN 'ORDERED_BY' AS type, bad UNION ALL
MATCH (a)-[r:ORIGINATES_AT]->(b) WHERE NOT ((a:Part AND b:Plant)) WITH count(r) AS bad RETURN 'ORIGINATES_AT' AS type, bad UNION ALL
MATCH (a)-[r:OWNED_BY]->(b) WHERE NOT ((a:Plant AND b:BusinessUnit)) WITH count(r) AS bad RETURN 'OWNED_BY' AS type, bad UNION ALL
MATCH (a)-[r:PART_OF]->(b) WHERE NOT ((a:Part AND b:Assembly)) WITH count(r) AS bad RETURN 'PART_OF' AS type, bad UNION ALL
MATCH (a)-[r:PLACED_WITH]->(b) WHERE NOT ((a:SupplierBackorder AND b:Supplier)) WITH count(r) AS bad RETURN 'PLACED_WITH' AS type, bad UNION ALL
MATCH (a)-[r:PLANNED_FULFILMENT_FROM]->(b) WHERE NOT ((a:OrderLine AND b:Warehouse)) WITH count(r) AS bad RETURN 'PLANNED_FULFILMENT_FROM' AS type, bad UNION ALL
MATCH (a)-[r:PRICES_PART]->(b) WHERE NOT ((a:Price AND b:Part)) WITH count(r) AS bad RETURN 'PRICES_PART' AS type, bad UNION ALL
MATCH (a)-[r:PRODUCT_FAMILY_OF]->(b) WHERE NOT ((a:MachineFamily AND b:BusinessUnit)) WITH count(r) AS bad RETURN 'PRODUCT_FAMILY_OF' AS type, bad UNION ALL
MATCH (a)-[r:PROFILES_PART]->(b) WHERE NOT ((a:PartCatalogProfile AND b:Part)) WITH count(r) AS bad RETURN 'PROFILES_PART' AS type, bad UNION ALL
MATCH (a)-[r:RECORDS_STATUS]->(b) WHERE NOT ((a:OrderStatusEvent AND b:OrderStatus)) WITH count(r) AS bad RETURN 'RECORDS_STATUS' AS type, bad UNION ALL
MATCH (a)-[r:REFERENCES_PART]->(b) WHERE NOT ((a:CartLine AND b:Part) OR (a:OrderLine AND b:Part)) WITH count(r) AS bad RETURN 'REFERENCES_PART' AS type, bad UNION ALL
MATCH (a)-[r:RELATED_COMPONENT]->(b) WHERE NOT ((a:Part AND b:Part)) WITH count(r) AS bad RETURN 'RELATED_COMPONENT' AS type, bad UNION ALL
MATCH (a)-[r:REQUIRES_PART]->(b) WHERE NOT ((a:ServicePlan AND b:Part)) WITH count(r) AS bad RETURN 'REQUIRES_PART' AS type, bad UNION ALL
MATCH (a)-[r:SAME_NAME_GROUP_AS]->(b) WHERE NOT ((a:Part AND b:Part)) WITH count(r) AS bad RETURN 'SAME_NAME_GROUP_AS' AS type, bad UNION ALL
MATCH (a)-[r:SERVES_FAMILY]->(b) WHERE NOT ((a:Dealer AND b:MachineFamily)) WITH count(r) AS bad RETURN 'SERVES_FAMILY' AS type, bad UNION ALL
MATCH (a)-[r:SHIPS_LINE]->(b) WHERE NOT ((a:Shipment AND b:OrderLine)) WITH count(r) AS bad RETURN 'SHIPS_LINE' AS type, bad UNION ALL
MATCH (a)-[r:SHIPS_TO_COUNTRY]->(b) WHERE NOT ((a:Warehouse AND b:Location)) WITH count(r) AS bad RETURN 'SHIPS_TO_COUNTRY' AS type, bad UNION ALL
MATCH (a)-[r:STOCKED_BY]->(b) WHERE NOT ((a:Part AND b:Dealer)) WITH count(r) AS bad RETURN 'STOCKED_BY' AS type, bad UNION ALL
MATCH (a)-[r:SUBCATEGORY_OF]->(b) WHERE NOT ((a:Category AND b:Category)) WITH count(r) AS bad RETURN 'SUBCATEGORY_OF' AS type, bad UNION ALL
MATCH (a)-[r:SUPPLIED_BY]->(b) WHERE NOT ((a:Part AND b:Supplier)) WITH count(r) AS bad RETURN 'SUPPLIED_BY' AS type, bad UNION ALL
MATCH (a)-[r:SUPPLIES_CATEGORY]->(b) WHERE NOT ((a:Supplier AND b:Category)) WITH count(r) AS bad RETURN 'SUPPLIES_CATEGORY' AS type, bad UNION ALL
MATCH (a)-[r:TO_CUSTOMER]->(b) WHERE NOT ((a:DeliveryEstimate AND b:Customer)) WITH count(r) AS bad RETURN 'TO_CUSTOMER' AS type, bad UNION ALL
MATCH (a)-[r:TO_DEALER]->(b) WHERE NOT ((a:DeliveryEstimate AND b:Dealer)) WITH count(r) AS bad RETURN 'TO_DEALER' AS type, bad UNION ALL
MATCH (a)-[r:VARIANT_OF]->(b) WHERE NOT ((a:MachineVariant AND b:Machine)) WITH count(r) AS bad RETURN 'VARIANT_OF' AS type, bad;

// V11 Forbidden relationship types
// expected: 0
MATCH ()-[r]->() WHERE type(r) IN ['ALTERNATIVE_TO', 'ASSOCIATED_WITH', 'BELONGS_TO', 'CONNECTED_TO', 'HAS', 'INTERCHANGEABLE', 'INTERCHANGEABLE_WITH', 'LINKED_TO', 'RELATED_TO', 'REPLACEMENT_FOR', 'SUPERSEDED_BY', 'SUPERSEDES'] RETURN count(r) AS forbidden;

// V12 Interchangeability asserted
// expected: 0
MATCH ()-[r]->() WHERE r.interchangeability_status IS NOT NULL AND r.interchangeability_status <> 'UNKNOWN' RETURN count(r) AS asserted;

// V13 Fitment status
// expected: CONDITIONAL 3, CONFIRMED 216
MATCH (:Part)-[f:FITS]->(:Machine) RETURN f.fitment_status AS status, count(*) AS c ORDER BY status;

// V14 Conditional fitments (must stay conditional)
// expected: NVM-1010-ST -> BTS-250: cross-compatible after 2019 unification; NVM-1020-ST -> BTS-250: cross-compatible after 2019 unification; NVM-1140-DT -> NV-7500: For tracked NV-7500 variant
MATCH (p:Part)-[f:FITS {fitment_status: 'CONDITIONAL'}]->(m:Machine) RETURN p.part_number, m.model_code, f.condition_note ORDER BY p.part_number;

// V15 Co-order duplication (mirrored pairs)
// expected: 0
MATCH (a:Part)-[:CO_ORDERED_WITH]->(b:Part) MATCH (b)-[:CO_ORDERED_WITH]->(a) RETURN count(*) AS mirrored;

// V16 Co-order relationships
// expected: c 75, merged 14
MATCH (:Part)-[r:CO_ORDERED_WITH]->(:Part) RETURN count(r) AS c, sum(CASE WHEN r.merged_source_record_ids IS NULL THEN 0 ELSE 1 END) AS merged;

// V17 Part -> machines (NVM-1010-HY)
// expected: NV-3200 CONFIRMED, NV-4500 CONFIRMED
MATCH (p:Part {part_number: 'NVM-1010-HY'})-[f:FITS]->(m:Machine) RETURN m.model_code, f.fitment_status ORDER BY m.model_code;

// V18 Machine -> parts (NV-4500)
// expected: 52
MATCH (m:Machine {model_code: 'NV-4500'})<-[:FITS]-(p:Part) RETURN count(p) AS parts;

// V19 Machine with no parts
// expected: KFT-120
MATCH (m:Machine) WHERE NOT (m)<-[:FITS]-(:Part) RETURN m.model_code;

// V20 Part -> category, sub-category, legacy
// expected: Hydraulics, Hydraulic hose, AS-771
MATCH (p:Part {part_number: 'NVM-1010-HY'})-[:IN_CATEGORY]->(c) MATCH (p)-[:IN_SUBCATEGORY]->(s) MATCH (p)-[:HAS_LEGACY_REFERENCE]->(l) RETURN c.name, s.name, l.legacy_part_number;

// V21 Part -> suppliers
// expected: Veldstra Hydraulics (demo) true 28 SYNTHETIC_DEMO; Rijnmond Hydraulic Supply (demo) false 10 SYNTHETIC_DEMO
MATCH (p:Part {part_number: 'NVM-1010-HY'})-[s:SUPPLIED_BY]->(x:Supplier) RETURN x.name, s.is_primary, s.lead_time_days, s.data_status ORDER BY s.is_primary DESC;

// V22 Part -> dealers
// expected: Brabant Heavy Parts (demo) 8; Drenthe Techniek (demo) 5; IJsselvallei Equipment (demo) 7
MATCH (p:Part {part_number: 'NVM-1010-HY'})-[s:STOCKED_BY]->(d:Dealer) RETURN d.name, s.available ORDER BY d.name;

// V23 Part -> warehouse inventory
// expected: Bakker Parts Depot Coevorden (demo) 9; Kessler Parts Depot Lingen (demo) 20; Noordveld Central Warehouse Assen (demo) 56; Regional Distribution Centre Zwolle (demo) 11
MATCH (p:Part {part_number: 'NVM-1010-HY'})-[s:AVAILABLE_AT]->(w:Warehouse) RETURN w.name, s.on_hand, s.reserved, s.available ORDER BY w.name;

// V24 Excluded dealer zero-rows are absent
// expected: 0
MATCH ()-[s:STOCKED_BY]->() WHERE s.inventory_id IN ['INV-0006', 'INV-0009', 'INV-0018', 'INV-0027', 'INV-0059', 'INV-0069', 'INV-0072', 'INV-0084', 'INV-0095', 'INV-0110', 'INV-0117', 'INV-0119', 'INV-0146', 'INV-0159', 'INV-0160', 'INV-0175', 'INV-0190', 'INV-0191', 'INV-0206', 'INV-0238', 'INV-0263', 'INV-0289', 'INV-0290', 'INV-0294', 'INV-0297', 'INV-0340'] RETURN count(s) AS imported;

// V25 Part -> orders
// expected: parts_ordered 14, orders 8
MATCH (p:Part)<-[:REFERENCES_PART]-(l:OrderLine)<-[:CONTAINS_LINE]-(o:Order) RETURN count(DISTINCT p) AS parts_ordered, count(DISTINCT o) AS orders;

// V26 Order -> customer and shipments
// expected: 8 rows; 4 orders with at least one shipment
MATCH (o:Order)-[:ORDERED_BY]->(c:Customer) OPTIONAL MATCH (o)-[:HAS_SHIPMENT]->(s:Shipment) RETURN o.order_id, c.name, count(s) AS shipments ORDER BY o.order_id;

// V27 Shipment -> tracking events
// expected: 9 shipments, 27 events
MATCH (s:Shipment)-[:HAS_TRACKING_EVENT]->(e:TrackingEvent) RETURN s.shipment_id, count(e) AS events ORDER BY s.shipment_id;

// V28 Service plan -> machine and parts
// expected: plans 60, machines 15, parts 33
MATCH (sp:ServicePlan)-[:FOR_MACHINE]->(m:Machine) OPTIONAL MATCH (sp)-[:REQUIRES_PART]->(p:Part) RETURN count(DISTINCT sp) AS plans, count(DISTINCT m) AS machines, count(DISTINCT p) AS parts;

// V29 No service jobs, alternatives, supersessions or risks
// expected: 0, 0
MATCH (n) WHERE n:ServiceJob OR n:Installation OR n:Request OR n:SourceRisk RETURN count(n) AS c UNION ALL MATCH ()-[r]->() WHERE type(r) IN ['ALTERNATIVE_TO','SUPERSEDES','SUPERSEDED_BY','REPLACEMENT_FOR','HAS_RISK'] RETURN count(r) AS c;

// V30 Trace part -> machine -> order -> shipment -> service
// expected: rows for NV-3200 and NV-4500; 4 service plans each
MATCH (p:Part {part_number: 'NVM-1010-HY'})-[:FITS]->(m:Machine) OPTIONAL MATCH (p)<-[:REFERENCES_PART]-(:OrderLine)<-[:CONTAINS_LINE]-(o:Order) OPTIONAL MATCH (o)-[:HAS_SHIPMENT]->(s:Shipment) OPTIONAL MATCH (sp:ServicePlan)-[:FOR_MACHINE]->(m) RETURN m.model_code, collect(DISTINCT o.order_id) AS orders, collect(DISTINCT s.shipment_id) AS shipments, count(DISTINCT sp) AS service_plans;

// V31 Impact analysis: part -> machines -> orders -> service plans
// expected: machines 2, orders 0, service_plans 1
MATCH (p:Part {part_number: 'NVM-1010-HY'}) OPTIONAL MATCH (p)-[:FITS]->(m:Machine) OPTIONAL MATCH (p)<-[:REFERENCES_PART]-(:OrderLine)<-[:CONTAINS_LINE]-(o:Order) OPTIONAL MATCH (p)<-[:REQUIRES_PART]-(sp:ServicePlan) RETURN count(DISTINCT m) AS machines, count(DISTINCT o) AS orders, count(DISTINCT sp) AS service_plans;

// V32 Provenance traversal
// expected: NV-3200 SOURCE_DERIVED machine_part_fitment FIT-0002 Catalog workbook (supplied); NV-4500 SOURCE_DERIVED machine_part_fitment FIT-0003 Catalog workbook (supplied)
MATCH (p:Part {part_number: 'NVM-1010-HY'})-[f:FITS]->(m:Machine) MATCH (d:DataSource {source_id: f.source_id}) RETURN m.model_code, f.provenance_type, f.source_sheet, f.source_record_id, f.source_ref, d.name ORDER BY m.model_code;

// V33 Idempotency check (run after a second import)
// expected: 1840 and 3812: unchanged after re-running every file
MATCH (n) RETURN count(n) AS nodes UNION ALL MATCH ()-[r]->() RETURN count(r) AS nodes;
